"""Walk a lab book the way a participant would, and report anything that breaks.

    python scripts/simulate_participant.py labs/week3.html
    python scripts/simulate_participant.py labs/week3.html labs/week3-activity.html

It reads the book's copy blocks in order and carries them out against a throwaway
copy of this repository. Claude Code is stood in for: prompts are not sent to a
model, but the files a prompt says it will write are created, so later steps that
depend on them behave as they would on a real machine.

What it catches, which reading cannot:
  - a command that refers to a file that does not exist yet at that point
  - steps in an order that cannot work
  - a prompt that names no output file, so the answer would land in the chat
  - Windows quoting and path traps
  - a book that uses Claude Code without ever starting it

What it cannot catch: whether a model's answer is any good. That is what the
rubric and the scoring step are for.

Exit code 0 means a clean walk. Standard library only.
"""

import html
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

FAKE_CLAUDE = r"""#!/usr/bin/env python3
# Stands in for Claude Code inside the walk. It answers --version, and answers
# `-p` non-interactive calls with the JSON shape the real CLI returns, creating
# whatever output file the instruction names so later steps behave realistically.
import json, os, re, sys

args = sys.argv[1:]
if args and args[0] == "--version":
    print("2.1.260 (Claude Code)")
    sys.exit(0)
if "-p" not in args and "--print" not in args:
    sys.exit(0)

prompt = sys.stdin.read()
model = args[args.index("--model") + 1] if "--model" in args else "sonnet"
named = {"opus": "claude-opus-5", "sonnet": "claude-sonnet-5",
         "haiku": "claude-haiku-4-5"}.get(model, model)

if "TOTAL: n/25" in prompt or "out of 25" in prompt:
    needed = re.findall(r"(?:prompts|week\d|rubrics|templates)/[\w./-]+\.md", prompt)
    missing = [f for f in needed if not os.path.exists(f)]
    if missing:
        result = "I could not find " + missing[0]
    else:
        result = ("1. First criterion - 4 - \"evidence\"\\n"
                  "2. Second criterion - 5 - \"evidence\"\\n"
                  "3. Third criterion - 4 - \"evidence\"\\n"
                  "4. Fourth criterion - 5 - \"evidence\"\\n"
                  "5. Fifth criterion - 3 - \"evidence\"\\n"
                  "TOTAL: 21/25")
else:
    for out in re.findall(r"week\d/[\w./-]+\.(?:md|html|csv)", prompt):
        folder = os.path.dirname(out)
        if folder:
            os.makedirs(folder, exist_ok=True)
        if not os.path.exists(out):
            with open(out, "w", encoding="utf-8") as fh:
                fh.write("# written by the simulated model\\n\\n"
                         "| # | a | b |\\n|---|---|---|\\n| 1 | x | y |\\n")
    result = "done: 7 items, 3 open questions"

size = len(prompt)
print(json.dumps({
    "type": "result", "is_error": False, "result": result,
    "total_cost_usd": round(0.05 + size / 40000, 4),
    "modelUsage": {named: {"inputTokens": 10, "outputTokens": max(600, 4000 - size // 3),
                           "cacheReadInputTokens": 90000 + size * 8,
                           "cacheCreationInputTokens": 30000}}}))
"""

REPO = Path(__file__).resolve().parents[1]
RUNNABLE = ("powershell", "prompt", "claude code")

complaints: list[tuple[str, str]] = []
state: dict = {}


def complain(kind: str, msg: str) -> None:
    complaints.append((kind, msg))
    print(f"  !! {kind}: {msg}")


def win(p: str) -> Path:
    p = p.replace("$env:USERPROFILE", str(state["home"])).replace("\\", "/").strip('"')
    return Path(p) if p.startswith("/") else state["cwd"] / p


def usage_line(size: int) -> str:
    out = max(600, 6000 - size // 3)
    return (f"claude-sonnet-5: 10 input, {out / 1000:.1f}k output, "
            f"{(90000 + size * 8) / 1000:.1f}k cache read, 30.0k cache write "
            f"(${0.05 + size / 30000:.2f})")


def claude_turn(prompt: str, label: str) -> None:
    """Stand in for a model turn: create whatever files the prompt says it writes."""
    if re.search(r"[Dd]o not edit any(thing| file)|[Dd]o not edit", prompt):
        state["usage"] = usage_line(len(prompt))
        return
    outs = re.findall(r"(?:week\d|labs|docs|data)/[A-Za-z0-9_./-]+\.(?:md|html|csv|json|txt)", prompt)
    outs = [o for o in outs if o.startswith("week")]
    if not outs:
        complain("LAB-BUG", f"{label}: this prompt names no output file, so the answer "
                            f"would land in the chat and be lost")
    for o in outs:
        p = state["cwd"] / o
        p.parent.mkdir(parents=True, exist_ok=True)
        if not p.exists():
            p.write_text("# generated by the simulated model\n\n| # | a | b |\n|---|---|---|\n| 1 | x | y |\n",
                         encoding="utf-8")
    state["usage"] = usage_line(len(prompt))


def sh(argv: list[str], label: str) -> subprocess.CompletedProcess:
    env = dict(os.environ, PATH=f"{state['bin']}{os.pathsep}{os.environ['PATH']}",
               USERPROFILE=str(state["home"]), HOME=str(state["home"]))
    r = subprocess.run(argv, cwd=state["cwd"], capture_output=True, text=True, env=env)
    if r.returncode != 0:
        complain("ERROR", f"{label}: `{' '.join(argv)[:80]}` exited {r.returncode}: "
                          f"{(r.stderr or r.stdout).strip()[-240:]}")
    return r


def ps(line: str, label: str, env: dict) -> None:
    line = line.strip()
    if not line or line.startswith("#"):
        return
    for k, v in env.items():
        line = line.replace("${" + k + "}", v).replace("$" + k, v)

    if "_block" in state:
        if line == "}":
            kind, head, body = state.pop("_block")
            if kind == "foreach":
                var, vals = head
                for v in vals:
                    for b in body:
                        ps(b, label, {**env, var: v})
            elif not win(head).exists():
                for b in body:
                    ps(b, label, env)
            return
        state["_block"][2].append(line)
        return
    m = re.match(r"foreach \(\$(\w+) in (.+)\) \{$", line)
    if m:
        state["_block"] = ("foreach", (m.group(1), [x.strip().strip("'") for x in m.group(2).split(",")]), [])
        return
    m = re.match(r'if \(-not \(Test-Path "?([^")]+)"?\)\) \{$', line)
    if m:
        state["_block"] = ("if", m.group(1), [])
        return

    if '"' in line and re.search(r'"[^"]*\$\d', line):
        complain("LAB-BUG", f"{label}: a dollar sign inside double quotes would be eaten by PowerShell")

    m = re.match(r"cd (.+)", line)
    if m:
        t = win(m.group(1))
        if not t.exists():
            complain("ERROR", f"{label}: cd {m.group(1)} - cannot find path")
            return
        state["cwd"] = t
        return
    m = re.match(r'if \(-not \(Test-Path "?([^")]+)"?\)\) \{ (.+) \}$', line)
    if m:
        if not win(m.group(1)).exists():
            ps(m.group(2), label, env)
        return
    if line.startswith("dir"):
        for a in (line[3:].split() or ["."]):
            p = win(a)
            hits = list(p.parent.glob(p.name)) if "*" in a else ([p] if p.exists() else [])
            if not hits:
                complain("ERROR", f"{label}: dir {a} - nothing there")
        return
    if line.startswith("type "):
        if not win(line[5:]).exists():
            complain("ERROR", f"{label}: type {line[5:].strip()} - cannot find path")
        return
    m = re.match(r'copy "?([^" ]+)"? "?([^" ]+)"?$', line)
    if m:
        src, dst = win(m.group(1)), win(m.group(2))
        if not src.exists():
            complain("ERROR", f"{label}: copy source missing: {m.group(1)}")
            return
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(src, dst)
        return
    # Directive verb: stands in for a participant editing files by hand.
    m = re.match(r"rewrite (\S+) (\S+) (\S+)$", line)
    if m:
        pattern, old, new = m.groups()
        target = win(pattern)
        hits = sorted(target.parent.glob(target.name))
        if not hits:
            complain("ERROR", f"{label}: hand-edit found nothing matching {pattern}")
            return
        for f in hits:
            f.write_text(f.read_text(encoding="utf-8").replace(old, new), encoding="utf-8")
        return
    m = re.match(r"mkdir (\S+) -Force \| Out-Null", line)
    if m:
        win(m.group(1)).mkdir(parents=True, exist_ok=True)
        return
    m = re.match(r"\(?Get-Content (\S+) -Raw\)?.*Set-Clipboard", line)
    if m:
        src = win(m.group(1))
        if not src.exists():
            complain("ERROR", f"{label}: Get-Content {m.group(1)} - cannot find path")
            return
        # The book puts an instruction on the clipboard for the participant to paste
        # into Claude Code. Hold it; it is sent when the session is next cleared.
        state["clipboard"] = src.read_text(encoding="utf-8", errors="replace")
        return
    m = re.match(r'Set-Content (\S+) "(.*)"$', line)
    if m:
        win(m.group(1)).write_text(m.group(2).replace("`n", "\n"), encoding="utf-8")
        return
    if line.startswith("Start-Process "):
        if not win(line.split()[1]).exists():
            complain("ERROR", f"{label}: Start-Process on a file that does not exist")
        return
    if line.startswith("code "):
        for a in line[5:].split():
            if a.startswith("--"):
                continue
            if not win(a).exists():
                complain("ERROR", f"{label}: code {a} - missing, so the editor would open a blank file")
        return
    if line in ("code .", "claude"):
        state["claude"] = True
        return
    if line.startswith("claude --version") or line.startswith("python --version"):
        return
    if line.startswith("git "):
        sh(["git"] + re.findall(r'"[^"]*"|\S+', line[4:]), label)
        return
    if line.startswith(("python ", "py ")):
        argv = [a.strip("'\"").replace("\\", "/") for a in re.findall(r"'[^']*'|\"[^\"]*\"|\S+", line.split(" ", 1)[1])]
        if any("PASTE" in a for a in argv):
            if not state.get("usage"):
                complain("LAB-BUG", f"{label}: asks for a usage line before any run has produced one")
                return
            argv = [state["usage"] if "PASTE" in a else a for a in argv]
        sh([sys.executable] + argv, label)
        return
    complain("SIM", f"{label}: the simulator does not understand this line: {line[:70]}")


def walk(book: Path) -> None:
    text = book.read_text(encoding="utf-8")
    steps = [(m.start(), m.group(1)) for m in re.finditer(r'<span class="step__n">(\d+)</span>', text)]

    def step_of(pos: int) -> str:
        s = "intro"
        for p, n in steps:
            if p < pos:
                s = f"step {n}"
        return s

    # Two kinds of thing happen in document order: copy blocks the participant runs,
    # and hand edits they make. A book declares the latter with a directive so the
    # walk can carry on past them:
    #     <!-- hand-edit: copy week3/impact.md week3/impact-final.md -->
    events = []
    for m in re.finditer(r'<span class="snippet__lang">([^<]+)</span>(.*?)<pre><code>(.*?)</code></pre>',
                         text, re.S):
        events.append((m.start(), "block", m.group(1), m.group(3)))
    for m in re.finditer(r"<!--\s*hand-edit:\s*(.+?)\s*-->", text, re.S):
        events.append((m.start(), "hand", "", m.group(1)))
    events.sort(key=lambda e: e[0])

    for pos, kind, lang, body in events:
        if kind == "hand":
            for ln in html.unescape(body).splitlines():
                ps(ln, f"{book.name} {step_of(pos)} [hand edit]", {})
            continue
        label = f"{book.name} {step_of(pos)}"
        code = html.unescape(body)
        low = lang.lower()
        if not any(low.startswith(r) for r in RUNNABLE):
            continue  # display-only: sample data, expected output
        if "only if" in low or "alternative" in low:
            continue  # conditional branches a passing participant does not take
        if low.startswith("powershell"):
            for ln in code.splitlines():
                ps(ln, label, {})
        elif low.startswith("claude code"):
            if not state.get("claude"):
                complain("LAB-BUG", f"{label}: a Claude Code command before Claude Code is started")
            for ln in code.splitlines():
                s = ln.strip()
                if s == "/clear":
                    state["usage"] = None
                    if state.get("clipboard"):
                        claude_turn(state.pop("clipboard"), label + " [pasted]")
                elif s == "/usage":
                    pass
                elif s.startswith("/"):
                    pass
                else:
                    complain("SIM", f"{label}: unrecognised Claude Code input: {s[:60]}")
        elif low.startswith("prompt"):
            if not state.get("claude"):
                complain("LAB-BUG", f"{label}: a prompt before Claude Code is started")
            claude_turn(code, label)


def main() -> None:
    books = [Path(b) if Path(b).is_absolute() else REPO / b for b in sys.argv[1:]]
    if not books:
        sys.exit("Give me one or more lab books, e.g. labs/week3.html")
    for b in books:
        if not b.exists():
            sys.exit(f"{b} does not exist")

    home = Path(tempfile.mkdtemp(prefix="sim-participant-"))
    repo = home / "Helios" / "helios-sandbox"
    repo.parent.mkdir(parents=True)
    def ignore(directory, names):
        drop = {".git", "__pycache__", ".pytest_cache"}
        if Path(directory).resolve() == REPO:
            # a participant's own week folders are their working area, never inherited
            drop |= {n for n in names if re.fullmatch(r"week\d+", n)}
        return drop & set(names)

    shutil.copytree(REPO, repo, ignore=ignore)
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "p@h.local"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "participant"], cwd=repo, check=True)
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "base"], cwd=repo, check=True)
    subprocess.run(["git", "checkout", "-qb", "sam/foundation"], cwd=repo, check=True)
    # An "origin" the books can fetch and merge from, holding the same content.
    origin = home / "origin.git"
    subprocess.run(["git", "clone", "-q", "--bare", str(repo), str(origin)], check=True)
    subprocess.run(["git", "remote", "add", "origin", str(origin)], cwd=repo, check=True)
    subprocess.run(["git", "fetch", "-q", "origin"], cwd=repo, check=True)
    subprocess.run(["git", "branch", "-qf", "main", "HEAD"], cwd=repo, check=True)
    subprocess.run(["git", "push", "-q", "origin", "main:main"], cwd=repo, check=True)

    binaries = home / "bin"
    binaries.mkdir()
    stub = binaries / "claude_stub.py"
    stub.write_text(FAKE_CLAUDE, encoding="utf-8")
    (binaries / "claude").write_text(
        f'#!/bin/sh\nexec "{sys.executable}" "{stub}" "$@"\n', encoding="utf-8")
    (binaries / "claude").chmod(0o755)
    (binaries / "code").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    (binaries / "code").chmod(0o755)

    state.update(home=home, cwd=repo, bin=binaries, claude=False, usage=None, clipboard=None)

    for b in books:
        print(f"walking {b.name} ...")
        walk(b)

    print(f"\n{len(complaints)} complaint(s)")
    for kind, msg in complaints:
        print(f"  [{kind}] {msg}")
    shutil.rmtree(home, ignore_errors=True)
    sys.exit(1 if complaints else 0)


if __name__ == "__main__":
    main()
